version: '3'

services:
  db:
    image: postgres
    stdin_open: true # docker run -i
    tty: true # docker run -t
    ports: 
      - "5432"
    environment:
      - POSTGRES_DB=caps
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
